### PR TITLE
V1.0.0 dev

### PR DESCRIPTION
**Pull request by jwildfire**

### CODE REVIEW

**Comment by jwildfire** [comment]
@brittsikora - version tagged 'v1.0.0-RC2' is ready for regression testing

**Comment by brittsikora** [comment]
Current version doesn't contain visit filter and isn't compatible with Firefox

**Comment by jwildfire** [comment]
It's not included by default, but settings for the visit filter are documented in this [issue](https://github.com/RhoInc/query-overview/issues/2#issuecomment-300917658). 

Things appear to be running as expected on FF 53.0.2 on Mac.

**Comment by brittsikora** [comment]
Visit filter is not appearing with the marking group filter - Jeremy has made the decision to remove the marking group filter from the defaults and include it in the customization. See issue #32.

Will need to deploy RC3 and finish testing

**Comment by brittsikora** [comment]
Query Overview Regression Tests
   
Filters and Controls
Group by Drop-down
[x] Change the input on the Group by filter, confirm that the data groups by the selected variable
 
Form Filter
[x] When the data is grouped by Form, change the input on the Form filter, confirm that the chart updates
 
Y-Axis Label Filter
[x] When the data is grouped by form, select the form label and confirm you can view the form: field data for the selected form.
 
Marking Groups Filter
[x] Enter settings object to render. Change the input on the Marking Groups filter and confirm the chart updates. 
 
Visit Filter
[x] When the previous settings objects have been entered, change the input on the Visit filter and confirm the chart updates.
 
Status Filter
[x] Select an option from the status filter, confirm the chart updates and the status is marked in the legend by a sheer grey box.
 
Filter using Legend
[x] Select a status label/colored box from the Query Status legend and confirm the chart updates. 
[x] Confirm the status is marked in the legend by a sheer grey box and the status is highlighted in the Status filter.
 
Site Filter
[x] Change the input on the Site filter, confirm the chart updates.
 
Bar Arrangement Toggle
[x] When bar arrangement is set to stacked, confirm that the y-axis has one bar for each variable.
[x] When bar arrangement is set to grouped, confirm that the y-axis has a set of bars for each status within a variable.
 
Show first N Groups
[x] When Group by is set to Form: Field, confirm that it displays 10 results.
[x] When Group by is set to Form: Field, select 25 under Show first N groups and confirm that it displays 25 results.
[x] When Group by is set to Form: Field, select All under Show first N groups and confirm that it displays >25 results.
 
Alphabetize
[x] Select the checkbox underneath Alphabetical? and confirm that the data has been alphabetized.
[x] Unselect the checkbox underneath Alphabetical? and confirm that the data returns to the default order.
 
Hover
[x] Hover over a form label to show the form name.
[x] Hover over a form: field label to show the form and field name.
[x] Hover over a bar to show the number of queries associated with that group and status.
 
Data Listing
[x] Confirm that clicking on a bar will open a linked table of records associated with that bar and the bar is filled in with a black line.
[x] When the listing is open, change the input on the data filters, confirm that the listing disappears along with the black line in the associated bar.
[x] When the listing is open, confirm that the Clear listing button causes the listing to disappear along with the black line in the associated bar.
 
Reset Button
[x] When the filters and controls have been used, confirm that selecting the Reset chart button clears the input and returns the chart it its default settings.

**Review by brittsikora — APPROVED** [review]

**Pull request merged**
