### PR TITLE
remove custom listing functionality and update codebase to work with …

### LINKED ISSUE #47: Add data export.

### LINKED ISSUE #50: Add listing manipulation functionality.

### LINKED ISSUE #51: query-overview not rendering anything using webcharts version v1.9.0-RC3
In the current pending version of webcharts, I'm not seeing anything loaded when I render the chart in CAT. I see the same behavior in all browsers.

image

### PR DESCRIPTION
**Pull request by samussiah**
…webcharts v1.9

Closes #47 
Closes #50 
Closes #51 
Closes #52

### CODE REVIEW

**Review by jwildfire — CHANGES_REQUESTED** [review]
Duplicate Clear Listing buttons

**Comment by jwildfire** [comment]
screen shot 2017-10-13 at 2 07 42 pm

**Comment by samussiah** [comment]
Ready for you again @jwildfire.

**Review by jwildfire — APPROVED** [review]
Works like a charm.

**Pull request merged**
